"""Tracked-files gate.

The repository is public and installs on-purpose from a checkout that lives outside
it. The installer's outputs (symlinks into that checkout, Claude Code's marketplace
path) are machine-local: tracked, they publish a home-directory layout and load
agent instructions from outside the repository on whichever machine reads them.
`.agents/on-purpose.json` records the plugin choice; the rest is regenerated by
running the installer again.

Checks against the git index rather than the working tree: no tracked symlink
resolves outside the repository, no tracked file names an absolute home-directory
path, and service/uv.lock is tracked. Card #441 adds the corpus gates: .gitignore
ignores a photo corpus folder wherever it lands in the checkout, no tracked file
sits under any other fixtures folder, and every frame in service/tests/fixtures/
is small and EXIF-free like the first one. The frame gate reads each blob from
the index, so it judges the bytes a push would carry, and decides from those
bytes -- never from the file's name -- which of them it has to judge.

Two checks read the working tree instead, because each judges what the next
commit would do rather than what the last one carried: that the lockfile is
current with service/pyproject.toml, and the ignore rules, which are checked
from the working-tree .gitignore because that is the file `git add -A` consults
when a corpus is about to be staged. The ignore verdict is the rule git matched
rather than its exit status, which reads the same whether a rule ignores a path
or re-includes it.
"""

import base64
import io
import re
import subprocess
from pathlib import Path

import pytest
from PIL import Image, UnidentifiedImageError

from conftest import FIXTURE, REPO, _load_tool, metadata_laden

# POSIX ERE, for git grep.
HOME_PATH = "/(Users|home)/[^/[:space:]`'\"]+/"


def _git(*args: str, check: bool = True, text: bool = True, repo: Path = REPO):
    return subprocess.run(
        ["git", "-C", str(repo), *args], check=check, capture_output=True, text=text
    )


def _index_bytes(path: str, repo: Path = REPO) -> bytes:
    """The blob staged for `path`: what a push carries, whatever is on disk."""
    return _git("cat-file", "-p", f":{path}", text=False, repo=repo).stdout


def _throwaway_repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir(exist_ok=True)
    _git("init", "-q", repo=repo)
    return repo


def _tracked_symlinks():
    for entry in _git("ls-files", "-s", "-z").stdout.split("\0"):
        if not entry:
            continue
        meta, path = entry.split("\t", 1)
        mode, blob, _stage = meta.split()
        if mode == "120000":
            yield path, _git("cat-file", "-p", blob).stdout


def test_no_tracked_symlink_leaves_the_repository():
    outside = []
    for path, target in _tracked_symlinks():
        resolved = ((REPO / path).parent / target).resolve()
        if not resolved.is_relative_to(REPO):
            outside.append(f"{path} -> {target}")
    assert not outside, (
        "tracked symlinks point outside the repository (machine-local install "
        f"output; keep it untracked and rerun the installer): {outside}"
    )


def test_no_tracked_file_names_a_home_directory_path():
    hits = _git("grep", "--cached", "-I", "-n", "-E", HOME_PATH, check=False)
    assert hits.returncode == 1, (
        "tracked files name an absolute home-directory path (machine-local, and "
        f"public once pushed):\n{hits.stdout}"
    )


def test_the_lockfile_is_tracked():
    """Card #425: docs/brief.md's stack contract names service/uv.lock as the
    lockfile, and CI installs from it; a lockfile that is not in git is not one."""
    tracked = _git("ls-files", "--", "service/uv.lock").stdout.splitlines()
    assert tracked == ["service/uv.lock"], "service/uv.lock is not tracked"


def test_the_lockfile_is_current_with_pyproject():
    """A lockfile that disagrees with service/pyproject.toml pins nothing: CI's
    `uv sync --locked` would refuse it, so the suite refuses it first."""
    # --offline: a current lock verifies from the lockfile alone (no index calls,
    # cold cache included), and a drifted one must fail here, not re-resolve
    # against PyPI from inside the test suite. The timeout bounds the subprocess.
    check = subprocess.run(
        ["uv", "lock", "--check", "--offline"],
        cwd=REPO / "service",
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert check.returncode == 0, check.stderr


# Card #441. Ignored: a corpus folder anywhere in the checkout. Not ignored: the
# one committed frame's folder. The rules are checked against a copy of
# .gitignore in a throwaway repository: `git check-ignore` on `fixtures/x.jpg`
# refuses a checkout where `fixtures` is a symlink to the corpus, and the
# verdict must not depend on what a given checkout has under that name.
CORPUS_PATHS = [
    # A symlink to the corpus, the way a checkout borrows one; it is not a
    # directory, so a directory-only rule (`fixtures/`) would let it through.
    "fixtures",
    "fixtures/x.jpg",
    "fixtures_full/x.jpg",
    "service/fixtures/x.jpg",
    "plugin/fixtures/x.jpg",
    "service/tests/quality/fixtures/x.jpg",
    "fixtures_full/nested/x.jpg",
    # A corpus folder nested under the re-included one. This is where
    # `!/service/tests/fixtures` could over-reach: the negation exempts the
    # committed frame's folder, and a corpus dropped inside it is still a
    # corpus. The root-only rules it replaces let both of these through.
    "service/tests/fixtures/fixtures/x.jpg",
    "service/tests/fixtures/fixtures_full/x.jpg",
]
# conftest.FIXTURE names the frame; git paths are POSIX strings from the root.
COMMITTED_FRAME = FIXTURE.relative_to(REPO).as_posix()
# The one folder .gitignore re-includes: neither it nor the frame it holds is
# ignored, and no other fixtures folder may hold a tracked file.
FIXTURES_DIR = FIXTURE.parent.relative_to(REPO).as_posix()


def test_the_frame_sits_under_the_repository_through_a_symlink(tmp_path):
    """pytest keeps symlinks in collected paths, so conftest.py can be reached
    through one. REPO is resolved; FIXTURE must be built the same way, or the
    two disagree and COMMITTED_FRAME raises at import, collecting nothing."""
    link = tmp_path / "link"
    link.symlink_to(REPO)
    conftest = _load_tool(link / "service" / "tests" / "conftest.py")
    assert conftest.FIXTURE.is_relative_to(conftest.REPO), (
        f"{conftest.FIXTURE} is not under {conftest.REPO}"
    )


def _check_ignore(tmp_path: Path, path: str, extra: str = "") -> tuple[bool, str]:
    """Whether the checkout's .gitignore ignores `path`, and the rule that says
    so (`source:line:pattern`, or why no rule matched).

    The verdict is the matched pattern, not the exit status: `git check-ignore
    -v` exits 0 for a negated rule too, printing the `!`-prefixed pattern that
    re-includes the path -- a path git would happily commit. `extra` appends
    rules to the copy, which is how that case is proven.
    """
    repo = _throwaway_repo(tmp_path)
    rules = (REPO / ".gitignore").read_bytes() + extra.encode()
    (repo / ".gitignore").write_bytes(rules)
    # 0: a rule matched, stdout "source:line:pattern\tpath"; 1: none did.
    verdict = _git("check-ignore", "-v", "--", path, check=False, repo=repo)
    if verdict.returncode != 0:
        return False, f"no rule matches {path}: {verdict.stderr.strip()}"
    rule = verdict.stdout.split("\t", 1)[0]
    return not rule.split(":", 2)[2].startswith("!"), rule


@pytest.mark.parametrize("path", CORPUS_PATHS)
def test_a_corpus_folder_is_ignored_anywhere_in_the_checkout(tmp_path, path):
    ignored, rule = _check_ignore(tmp_path, path)
    assert ignored, f"{path} is committable: {rule}"
    # The rule is the checkout's own, not a global excludes file git also reads.
    assert rule.startswith(".gitignore:"), rule


def test_a_negation_is_not_an_ignore(tmp_path):
    """The check that makes the corpus gate above mean anything. A negated rule
    re-includes the path, and `git check-ignore -v` still exits 0 on it: read
    that status alone and `!/fixtures` in .gitignore would leave the corpus
    symlink committable with every case above still passing."""
    ignored, rule = _check_ignore(tmp_path, "fixtures", extra="\n!/fixtures\n")
    assert not ignored, f"a negated rule was read as an ignore: {rule}"
    assert rule.endswith(":!/fixtures"), rule


@pytest.mark.parametrize("path", [COMMITTED_FRAME, FIXTURES_DIR])
def test_the_committed_frame_is_not_ignored(tmp_path, path):
    ignored, rule = _check_ignore(tmp_path, path)
    assert not ignored, f"{path} is ignored: {rule}"


# Card #441, Done-when 2. service/tests/fixtures/ holds one frame, downscaled
# and stripped (157 KB, no EXIF; 9351e64). A second frame is committable only
# on the same terms: under the ceiling and carrying no camera metadata, which
# the secret scanner does not read. And no tracked file may sit under any other
# fixtures folder, so a corpus cannot slip in even if the ignore rule is edited.
# Every tracked fixture is gated as a frame unless its blob is text and Pillow
# reads no image in it, whatever the fixture is called: an allowlist of image
# suffixes would let a raw (CR3, DNG), HEIC or BMP in unopened, and a raw
# carries the whole camera record, while an exemption by suffix would let the
# same bytes in under a .txt name. Text alone does not exempt either: the ASCII
# Netpbm formats (P1/P2/P3) and XPM are images whose bytes decode as text, and a
# text file can carry an image base64-encoded (a data URI, a JSON string).
FRAME_CEILING = 400 * 1024
CORPUS_DIRS = {"fixtures", "fixtures_full"}
# A run of the base64 alphabet long enough to hold an image header, unbroken
# (a data URI, a JSON string) or wrapped across lines (a 76-column dump).
BASE64_RUN = re.compile(rb"[A-Za-z0-9+/\r\n]{64,}")
# A wrapped dump's first full line. A run spans line breaks, so it also takes
# the tail of the line above the dump (uuencode's `begin-base64 644 x.jpg`, a
# MIME header, a heading); the dump, and the image, start at this line.
DUMP_LINE = re.compile(rb"^[A-Za-z0-9+/]{64,}", re.MULTILINE)


def _opened(blob: bytes) -> tuple[Image.Image | None, bool]:
    """The image Pillow reads from `blob` (None when it reads none), and
    whether it recognised an image format there at all. The gate's one
    reading of what a blob is; its callers close what they open.

    Only UnidentifiedImageError means no format. A header that matches a
    format's magic and then does not parse -- text opening `P1 fix`, a frame
    cut short -- raises ValueError or OSError: recognised, and unreadable.
    DecompressionBombError is neither, and propagates."""
    try:
        return Image.open(io.BytesIO(blob)), True
    except UnidentifiedImageError:
        return None, False
    except (ValueError, OSError):
        return None, True


def _is_image(blob: bytes, recognised: bool = False) -> bool:
    """Whether Pillow reads an image from `blob`, whatever it decodes as; or,
    with `recognised`, whether it recognises an image format there at all."""
    image, known = _opened(blob)
    if image is None:
        return recognised and known
    image.close()
    return True


def _frame_problems(data: bytes) -> list[str]:
    """Why `data` (a blob from the index) is not a committable frame."""
    problems = []
    size = len(data)
    if size > FRAME_CEILING:
        problems.append(f"{size} bytes, over the {FRAME_CEILING} byte ceiling")
    image, _recognised = _opened(data)
    if image is None:
        problems.append("not an image the gate can read")
    else:
        with image:
            if image.getexif() or "exif" in image.info:
                problems.append("carries EXIF")
    return problems


def _is_stray_fixture(path: str) -> bool:
    """A corpus-named directory component anywhere in the path, except the
    one that is exactly service/tests/fixtures: a corpus folder nested under
    the exempt folder is still another corpus folder."""
    exempt = FIXTURES_DIR.split("/")
    parts = path.split("/")[:-1]
    return any(
        part in CORPUS_DIRS and parts[: i + 1] != exempt
        for i, part in enumerate(parts)
    )


def _stray_fixture_paths(tracked):
    """Tracked paths under a fixtures folder other than service/tests/fixtures."""
    return [path for path in tracked if path and _is_stray_fixture(path)]


def _is_text(blob: bytes) -> bool:
    """Whether a blob decodes as text. Read from the bytes, because a name is
    not evidence of what was committed -- and not exempting on its own, because
    an image can be text too."""
    try:
        blob.decode("utf-8")
    except UnicodeDecodeError:
        return False
    return b"\0" not in blob


def _embeds_image(blob: bytes) -> bool:
    """Whether a text blob carries an image base64-encoded: any run of the
    alphabet, once its line breaks are dropped, in which Pillow recognises an
    image format, readable or not. A JSON string's `\\n` escapes end a run,
    so a wrapped dump's first run is an image cut short, which Pillow cannot
    read: it counts, and so does random base64 that opens with a BMP, PCX or
    SGI signature. The gate fails closed on what it cannot read. A run is
    decoded from its first full line, so the line above a dump is not read
    as the front of the image."""
    for run in BASE64_RUN.findall(blob):
        line = DUMP_LINE.search(run)
        data = run[line.start() if line else 0 :].translate(None, b"\r\n")
        decoded = base64.b64decode(data[: len(data) // 4 * 4])
        if _is_image(decoded, recognised=True):
            return True
    return False


def _gated_fixtures(blobs: dict[str, bytes]) -> list[str]:
    """Tracked fixtures the frame gate opens: every one whose indexed blob is
    an image's, or is not a text file's, or carries an image as base64. An
    image can be text -- Pillow reads the ASCII Netpbm formats and XPM -- and
    text can hold one, so only a blob that is text, no image Pillow reads, and
    carries none is exempt. A carrier is refused whole: the gate reads a frame
    as one image, and cannot vouch for one inside another file. Over the
    ceiling, text Pillow recognises an image format in is gated even when it
    cannot read it (an XPM that names a colour): a text image carries no EXIF
    Pillow reads, so the ceiling is the one check that could refuse it."""
    return [
        path
        for path, blob in blobs.items()
        if _is_image(blob, recognised=len(blob) > FRAME_CEILING)
        or not _is_text(blob)
        or _embeds_image(blob)
    ]


def _frame(image: Image.Image | None = None, **save) -> bytes:
    """A JPEG's bytes, the way the gate sees a blob."""
    buffer = io.BytesIO()
    (image or Image.new("RGB", (8, 8))).save(buffer, format="JPEG", **save)
    return buffer.getvalue()


def _ascii_frame(size: tuple[int, int] = (300, 300)) -> bytes:
    """An ASCII Netpbm frame's bytes: an image Pillow reads whose bytes are
    also UTF-8 with no NUL, and over the ceiling at this size."""
    values = ((i * 7) % 256 for i in range(size[0] * size[1] * 3))
    body = " ".join(f"{value:3d}" for value in values)
    return f"P3\n{size[0]} {size[1]}\n255\n{body}\n".encode()


def test_a_frame_over_the_ceiling_is_refused():
    # Noise does not compress: 1200 x 800 at quality 100 is well over 1 MB.
    big = _frame(Image.effect_noise((1200, 800), 64), quality=100)
    assert any("over the" in problem for problem in _frame_problems(big))


def _tagged_frame(tmp_path: Path) -> bytes:
    """The camera-record-laden frame the staging test is proven against."""
    path = tmp_path / "tagged.jpg"
    metadata_laden(path)
    return path.read_bytes()


def test_a_frame_with_exif_is_refused(tmp_path):
    assert _frame_problems(_tagged_frame(tmp_path)) == ["carries EXIF"]


def test_a_small_stripped_frame_passes():
    assert _frame_problems(_frame()) == []


def test_the_gate_judges_the_index_not_the_working_tree(tmp_path):
    """What a push carries is the staged blob. A clean frame staged and then
    overwritten on disk by a tagged one still passes; the reverse is refused."""
    repo = _throwaway_repo(tmp_path)
    plain, tagged = _frame(), _tagged_frame(tmp_path)

    (repo / "frame.jpg").write_bytes(plain)
    _git("add", "frame.jpg", repo=repo)
    (repo / "frame.jpg").write_bytes(tagged)
    assert _frame_problems(_index_bytes("frame.jpg", repo=repo)) == []

    _git("add", "frame.jpg", repo=repo)
    (repo / "frame.jpg").write_bytes(plain)
    assert _frame_problems(_index_bytes("frame.jpg", repo=repo)) == [
        "carries EXIF"
    ]


def test_a_frame_the_gate_cannot_read_is_refused():
    # A raw file (CR3, DNG, HEIC) carries the full camera record and Pillow
    # cannot read it, so the gate cannot prove it stripped: refused, by name.
    raw = bytes(range(256)) * 8
    assert _frame_problems(raw) == ["not an image the gate can read"]


def test_a_blob_pillow_raises_on_is_refused_by_name():
    """A header that matches a format's magic and then does not parse makes
    Pillow raise ValueError or OSError, not UnidentifiedImageError. The gate
    cannot read it, so it is refused under its path like a raw, not with a
    traceback that names no file."""
    blobs = {
        "service/tests/fixtures/second.ppm": b"P6\n" + bytes(range(256)) * 4,
        "service/tests/fixtures/second.jpg": _frame()[:57],
    }
    assert _gated_fixtures(blobs) == list(blobs)
    for blob in blobs.values():
        assert _frame_problems(blob) == ["not an image the gate can read"]


def test_every_fixture_but_a_text_file_is_gated():
    # The gate selects by what a fixture's blob is not (a text file), never by
    # an allowlist of image suffixes: a frame under any other suffix is still a
    # frame, and one the gate never opens is one it never refuses.
    frame, raw = _frame(), bytes(range(256)) * 8
    blobs = {
        COMMITTED_FRAME: frame,
        "service/tests/fixtures/download-lines.txt": b"one\ntwo\n",
        "service/tests/fixtures/second.CR3": raw,
        "service/tests/fixtures/second.dng": raw,
        "service/tests/fixtures/second.bmp": frame,
    }
    assert _gated_fixtures(blobs) == [
        COMMITTED_FRAME,
        "service/tests/fixtures/second.CR3",
        "service/tests/fixtures/second.dng",
        "service/tests/fixtures/second.bmp",
    ]


def test_camera_bytes_under_a_text_name_are_still_gated(tmp_path):
    """A fixture is exempt for what its indexed blob is, never for what it is
    called. Exempting `.txt` by name let an oversized or EXIF-bearing frame be
    committed as second.txt and skip both checks."""
    renamed = "service/tests/fixtures/second.txt"
    tagged = _tagged_frame(tmp_path)
    blobs = {
        "service/tests/fixtures/download-lines.txt": b"one\ntwo\n",
        renamed: tagged,
    }
    assert _gated_fixtures(blobs) == [renamed]
    assert _frame_problems(tagged) == ["carries EXIF"]


def test_an_ascii_frame_is_gated_whatever_it_decodes_as():
    """Text is not evidence either. Pillow reads the ASCII Netpbm formats
    (P1/P2/P3) and XPM, whose bytes decode as UTF-8 with no NUL, so exempting
    every text blob let an oversized frame in under .ppm and under .txt alike."""
    ascii_frame = _ascii_frame()
    named = "service/tests/fixtures/second.ppm"
    renamed = "service/tests/fixtures/second.txt"
    blobs = {
        "service/tests/fixtures/download-lines.txt": b"one\ntwo\n",
        named: ascii_frame,
        renamed: ascii_frame,
    }
    assert _gated_fixtures(blobs) == [named, renamed]
    assert any("over the" in problem for problem in _frame_problems(ascii_frame))


def test_text_pillow_raises_on_is_exempt():
    """Some ordinary text opens like an image header -- a first line of `P1 `
    and a word matches Netpbm's magic, `SIMPLE  =  T` matches FITS' -- and
    Pillow raises ValueError or OSError parsing the rest. It reads no image
    there, so the text is exempt, as it was before text was opened."""
    blobs = {
        "service/tests/fixtures/download-lines.txt": b"one\ntwo\n",
        "service/tests/fixtures/plan.txt": b"P1 fix the gate\nP2 tidy the docs\n",
        "service/tests/fixtures/header.txt": b"SIMPLE  =  T\n",
    }
    assert _gated_fixtures(blobs) == []


def test_an_ascii_frame_pillow_raises_on_is_gated_over_the_ceiling():
    """Nor is an image Pillow raises on. XPM names colours (`c black`) as well
    as spelling them `#rrggbb`, and Pillow reads only the second, so it
    recognises this frame and raises ValueError. Exempted as text Pillow reads
    no image in, it went in at any size. A text image carries no EXIF Pillow
    reads, so the ceiling is the one check that could refuse it."""
    width, height = 700, 600
    rows = b"\n".join(b'"' + b"ab" * (width // 2) + b'",' for _ in range(height))
    xpm = (
        b'/* XPM */\nstatic char *frame[] = {\n"%d %d 2 1",\n'
        b'"a c black",\n"b c #ffffff",\n' % (width, height)
    ) + rows + b"\n};\n"
    named = "service/tests/fixtures/second.xpm"
    blobs = {
        "service/tests/fixtures/download-lines.txt": b"one\ntwo\n",
        named: xpm,
    }
    assert _gated_fixtures(blobs) == [named]
    assert any("over the" in problem for problem in _frame_problems(xpm))


def test_an_image_carried_as_base64_text_is_gated(tmp_path):
    """Nor is a text container. An image base64-encoded inside a text fixture
    is still the image, camera record and all, in the shapes this repository
    writes one: a data URI (an SVG's embedded bitmap, the review sheet's
    thumbnails, the OpenAI request body), a bare JSON string (the Anthropic
    request body), a dump wrapped at 76 columns, and that dump as a JSON
    string. Each decodes as text Pillow reads no image in, so each let a
    tagged frame past both checks. The last one's `\\n` escapes end each run,
    so its first run is the frame cut short, which Pillow recognises and
    raises on: a crash that named no file, and no image once caught.

    A dump under a line of text is the same frame: `uuencode -m` writes one
    under `begin-base64 644 <name>`, a MIME part under its headers, a note
    under a heading. A run of the alphabet spans line breaks, so it took the
    tail of the line above (`jpg`, `base64`, `Frame`) and decoded that in
    front of the image, which Pillow then did not recognise."""
    tagged = _tagged_frame(tmp_path)
    inline = base64.b64encode(tagged)
    dump = base64.encodebytes(tagged)
    # A JSON writer escapes each of the dump's line breaks as `\n`.
    escaped = dump.replace(b"\n", rb"\n")
    carriers = {
        "service/tests/fixtures/second.svg": (
            b'<svg xmlns="http://www.w3.org/2000/svg">'
            b'<image href="data:image/jpeg;base64,' + inline + b'"/></svg>\n'
        ),
        "service/tests/fixtures/request.json": (
            b'{"source": {"type": "base64", "media_type": "image/jpeg", '
            b'"data": "' + inline + b'"}}\n'
        ),
        "service/tests/fixtures/second.b64": dump,
        "service/tests/fixtures/wrapped.json": (
            b'{"source": {"type": "base64", "media_type": "image/jpeg", '
            b'"data": "' + escaped + b'"}}\n'
        ),
        "service/tests/fixtures/second.uu": (
            b"begin-base64 644 second.jpg\n" + dump + b"====\n"
        ),
        "service/tests/fixtures/second.eml": (
            b"Content-Type: image/jpeg\r\n"
            b"Content-Transfer-Encoding: base64\r\n\r\n"
            + dump.replace(b"\n", b"\r\n")
        ),
        "service/tests/fixtures/notes.md": b"# Frame\n\n" + dump,
    }
    blobs = {
        "service/tests/fixtures/download-lines.txt": b"one\ntwo\n",
        # base64 that decodes to no image is text like any other.
        "service/tests/fixtures/noise.b64": base64.encodebytes(bytes(range(256)) * 8),
        **carriers,
    }
    assert _gated_fixtures(blobs) == list(carriers)
    for path in carriers:
        assert _frame_problems(blobs[path]) == ["not an image the gate can read"]


def test_stray_fixture_paths_are_named():
    tracked = [
        COMMITTED_FRAME,
        "service/tests/fixtures/download-lines.txt",
        "fixtures_dev_labels.json",
        "service/fixtures/x.jpg",
        "plugin/fixtures/x.jpg",
        "fixtures_full/nested/x.jpg",
        "fixtures/x.jpg",
        # Under the exempt folder, but inside another corpus folder nested there.
        "service/tests/fixtures/fixtures_full/x.jpg",
        "service/tests/fixtures/fixtures/x.jpg",
        "",
    ]
    assert _stray_fixture_paths(tracked) == [
        "service/fixtures/x.jpg",
        "plugin/fixtures/x.jpg",
        "fixtures_full/nested/x.jpg",
        "fixtures/x.jpg",
        "service/tests/fixtures/fixtures_full/x.jpg",
        "service/tests/fixtures/fixtures/x.jpg",
    ]


def test_no_tracked_file_sits_under_another_fixtures_folder():
    stray = _stray_fixture_paths(_git("ls-files", "-z").stdout.split("\0"))
    assert not stray, f"a corpus is tracked outside {FIXTURES_DIR}: {stray}"


def test_every_committed_frame_is_small_and_exif_free():
    # ls-files -z terminates each path, so the split leaves a trailing empty.
    tracked = _git("ls-files", "-z", "--", FIXTURES_DIR).stdout.split("\0")
    blobs = {path: _index_bytes(path) for path in tracked if path}
    frames = _gated_fixtures(blobs)
    assert COMMITTED_FRAME in frames, "the smoke test's frame is not tracked"
    refused = {p: _frame_problems(blobs[p]) for p in frames}
    refused = {p: problems for p, problems in refused.items() if problems}
    assert not refused, (
        "a committed frame is not small and stripped like the first one: "
        f"{refused}"
    )
