"""Tracked-files gate.

The repository is public and installs on-purpose from a checkout that lives outside
it. The installer's outputs (symlinks into that checkout, Claude Code's marketplace
path) are machine-local: tracked, they publish a home-directory layout and load
agent instructions from outside the repository on whichever machine reads them.
`.agents/on-purpose.json` records the plugin choice; the rest is regenerated by
running the installer again.

Checks against the git index rather than the working tree: no tracked symlink
resolves outside the repository, no tracked file names an absolute home-directory
path, and service/uv.lock is tracked. One check against the working tree: that
lockfile is current with service/pyproject.toml.
"""

import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
# POSIX ERE, for git grep.
HOME_PATH = "/(Users|home)/[^/[:space:]`'\"]+/"


def _git(*args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(REPO), *args], check=check, capture_output=True, text=True
    )


def _tracked_symlinks():
    for entry in _git("ls-files", "-s", "-z").stdout.split("\0"):
        if not entry:
            continue
        meta, path = entry.split("\t", 1)
        mode, blob, _stage = meta.split()
        if mode == "120000":
            yield path, _git("cat-file", "-p", blob).stdout


def test_no_tracked_symlink_leaves_the_repository():
    outside = []
    for path, target in _tracked_symlinks():
        resolved = ((REPO / path).parent / target).resolve()
        if not resolved.is_relative_to(REPO):
            outside.append(f"{path} -> {target}")
    assert not outside, (
        "tracked symlinks point outside the repository (machine-local install "
        f"output; keep it untracked and rerun the installer): {outside}"
    )


def test_no_tracked_file_names_a_home_directory_path():
    hits = _git("grep", "--cached", "-I", "-n", "-E", HOME_PATH, check=False)
    assert hits.returncode == 1, (
        "tracked files name an absolute home-directory path (machine-local, and "
        f"public once pushed):\n{hits.stdout}"
    )


def test_the_lockfile_is_tracked():
    """Card #425: docs/brief.md's stack contract names service/uv.lock as the
    lockfile, and CI installs from it; a lockfile that is not in git is not one."""
    tracked = _git("ls-files", "--", "service/uv.lock").stdout.splitlines()
    assert tracked == ["service/uv.lock"], "service/uv.lock is not tracked"


def test_the_lockfile_is_current_with_pyproject():
    """A lockfile that disagrees with service/pyproject.toml pins nothing: CI's
    `uv sync --locked` would refuse it, so the suite refuses it first."""
    # --offline: a current lock verifies from the lockfile alone (no index calls,
    # cold cache included), and a drifted one must fail here, not re-resolve
    # against PyPI from inside the test suite. The timeout bounds the subprocess.
    check = subprocess.run(
        ["uv", "lock", "--check", "--offline"],
        cwd=REPO / "service",
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert check.returncode == 0, check.stderr
