local t = require('harness')
local Json = require('MelampusJson')

t.test('objects and arrays', function()
	local v = Json.decode('{"a":1,"b":[1,2,3]}')
	t.equals(v.a, 1); t.equals(#v.b, 3)
end)
t.test('nested candidate shape', function()
	local v = Json.decode('{"candidates":[{"common_name":"Egretta tricolor","confidence":0.95}]}')
	t.equals(v.candidates[1].common_name, 'Egretta tricolor')
	t.equals(v.candidates[1].confidence, 0.95)
end)
t.test('booleans and null', function()
	local v = Json.decode('{"t":true,"f":false,"n":null}')
	t.isTrue(v.t); t.isFalse(v.f); t.isTrue(Json.isNull(v.n))
end)
t.test('escapes survive', function()
	t.equals(Json.decode('{"s":"a\\"b\\\\c\\nd"}').s, 'a"b\\c\nd')
end)
t.test('unicode escapes decode to utf-8', function()
	t.equals(Json.decode('{"s":"caf\\u00e9"}').s, 'caf\195\169')
end)
t.test('braces inside strings do not confuse the parser', function()
	t.equals(Json.decode('{"r":"shape {like this}","t":"bird"}').t, 'bird')
end)
t.test('negative and exponent numbers', function()
	local v = Json.decode('{"a":-1.5,"b":1e3}')
	t.equals(v.a, -1.5); t.equals(v.b, 1000)
end)
t.test('malformed input returns an error rather than raising', function()
	for _, bad in ipairs({ '{"a":1', 'not json', '{"a":1} extra', '' }) do
		local v, e = Json.decode(bad)
		t.isNil(v, 'accepted malformed input: ' .. bad)
		t.isNotNil(e, 'no error message for: ' .. bad)
	end
end)

return t.summary()
