"""Write a wildlife sightings log as a Markdown note.

Melampus knows what was photographed; EXIF knows when. Together that is a life
list and a per-outing log, which is the shape a personal assistant can actually
use — "what did I see in June", "when did I first photograph an Anhinga".

Aggregation is per ENCOUNTER, never per frame. A 216-frame burst of one heron is
one sighting, not 216, and per-frame counts would make common subjects look
overwhelming while rare ones vanish.

Unreviewed identifications are marked as such. The whole project's governing rule
is that a wrong label is worse than no label, and that applies with more force
here: it is read later as settled fact.

    python tools/export_to_vault.py fixtures_full stage1_full_results.json \\
        ~/notes/wildlife-sightings.md
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from cluster_encounters import cluster  # noqa: E402

DEFAULT_LOCATION = "Merritt Island National Wildlife Refuge, FL"


def norm(name: str | None) -> str:
    return "".join(c for c in (name or "").lower() if c.isalnum())


def titlecase(name: str) -> str:
    small = {"of", "the", "and"}
    return " ".join(
        w if w in small else "-".join(p.capitalize() for p in w.split("-"))
        for w in (name or "").split()
    )


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("folder", type=Path)
    ap.add_argument("results", type=Path)
    ap.add_argument("out", type=Path)
    ap.add_argument("--gap", type=float, default=10.0)
    ap.add_argument("--location", default=DEFAULT_LOCATION)
    ap.add_argument("--min-agreement", type=float, default=0.6,
                    help="drop encounters whose frames disagree more than this")
    ap.add_argument("--reviewed", action="store_true",
                    help="mark entries as human-confirmed rather than provisional")
    args = ap.parse_args(argv[1:])

    records = {r["file"]: r for r in json.loads(args.results.read_text("utf-8"))}
    encounters = cluster(sorted(args.folder.glob("*.jpg")), args.gap)

    # species -> list of (date, encounter_index, frames, agreement, confidence)
    sightings: dict[str, list[tuple]] = defaultdict(list)
    by_date: dict[str, list[tuple]] = defaultdict(list)
    dropped_unstable = 0
    dropped_abstain = 0
    total_encounters = 0

    for enc in encounters:
        names: list[str] = []
        confs: list[float] = []
        for frame in enc.frames:
            rec = records.get(frame.name)
            if rec is None or rec.get("status") != "ok":
                continue
            ident = rec.get("identification") or {}
            cands = sorted(ident.get("candidates", []), key=lambda c: -c.get("confidence", 0))
            if ident.get("abstain") or not cands:
                continue
            names.append(titlecase(cands[0].get("common_name", "")))
            confs.append(float(cands[0].get("confidence", 0)))
        if not names:
            dropped_abstain += 1
            continue
        total_encounters += 1

        counts = Counter(norm(n) for n in names)
        key, hits = counts.most_common(1)[0]
        agreement = hits / len(names)
        if agreement < args.min_agreement:
            dropped_unstable += 1
            continue

        species = next(n for n in names if norm(n) == key)
        when = enc.start.date().isoformat() if enc.start else "unknown"
        best = max(confs) if confs else 0.0
        sightings[species].append((when, enc.index, enc.size, agreement, best))
        by_date[when].append((species, enc.size, agreement))

    # Write the note even when nothing qualified. Bailing out would leave the
    # previous export sitting in the vault looking current, which is worse than
    # an empty list that says plainly that nothing was confidently identified.
    stamp = datetime.fromtimestamp(args.results.stat().st_mtime).date().isoformat()
    status = "human-confirmed" if args.reviewed else "PROVISIONAL — not yet human-reviewed"

    out: list[str] = [
        "---",
        "tier: open",
        "status: GENERATED",
        f"reviewed: {stamp}",
        "---",
        "",
        "# Wildlife sightings",
        "",
        f"Species photographed, from [[melampus]]. **{status}.**",
        "",
        "> Generated file — regenerated by `tools/export_to_vault.py`, so hand edits are",
        "> lost on the next run. Correct identifications in Melampus's review sheet",
        "> instead and re-export.",
        "",
    ]

    if not args.reviewed:
        out += [
            "> [!warning] These identifications are unreviewed model output.",
            "> Roughly one in five is expected to be wrong, and confusable pairs —",
            "> Tricolored versus Little Blue Heron especially — are unreliable. Treat",
            "> this as a record of what was *probably* seen, not a verified life list.",
            "",
        ]

    # ---------------------------------------------------------------- life list
    out += [
        f"## Life list — {len(sightings)} species",
        "",
        "One row per species. Sightings are counted per shooting encounter, not per",
        "frame, so a long burst of one bird counts once.",
        "",
    ]
    if not sightings:
        out += [
            "Nothing was confidently identified in this run. Every encounter either",
            "abstained or disagreed with itself across frames — see Provenance below.",
            "",
        ]
    else:
        out += [
            "| species | first seen | last seen | sightings | frames | agreement |",
            "| --- | --- | --- | ---: | ---: | ---: |",
        ]
    for species in sorted(sightings, key=lambda s: (-len(sightings[s]), s)):
        entries = sightings[species]
        dates = sorted(e[0] for e in entries)
        frames = sum(e[2] for e in entries)
        agree = sum(e[3] for e in entries) / len(entries)
        out.append(
            f"| {species} | {dates[0]} | {dates[-1]} | {len(entries)} | {frames} | {agree:.0%} |"
        )

    # ------------------------------------------------------------- by outing
    out += ["", "## By outing", ""]
    for when in sorted(by_date):
        seen = by_date[when]
        species_here = sorted({s for s, _, _ in seen})
        out += [
            f"### {when} — {args.location}",
            "",
            f"{len(seen)} encounters, {len(species_here)} species, "
            f"{sum(f for _, f, _ in seen)} frames.",
            "",
        ]
        agg: dict[str, list[int]] = defaultdict(lambda: [0, 0])
        for species, frames, _ in seen:
            agg[species][0] += 1
            agg[species][1] += frames
        for species in sorted(agg, key=lambda s: (-agg[s][0], s)):
            n, frames = agg[species]
            times = "once" if n == 1 else f"{n} times"
            out.append(f"- **{species}** — {times}, {frames} frames")
        out.append("")

    # ------------------------------------------------------------- provenance
    out += [
        "## Provenance",
        "",
        f"- Source: `{args.results.name}` from the Melampus identification run",
        f"- Encounters grouped by capture-time gaps over {args.gap:.0f}s",
        f"- {total_encounters} encounters carried an identification; "
        f"{dropped_abstain} abstained entirely",
        f"- {dropped_unstable} dropped for frame-to-frame disagreement below "
        f"{args.min_agreement:.0%}",
        "- Location is the configured default; no photograph in this set carries GPS",
        "",
    ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {args.out}")
    print(f"  species   : {len(sightings)}")
    print(f"  encounters: {total_encounters} kept, {dropped_unstable} unstable, "
          f"{dropped_abstain} abstained")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
